num1=input("Enter first number:")
num2=input("Enter second number:")
#operations on two numbers
addition=float(num1)+float(num2)
subtraction=float(num1)-float(num2)
multiplication=float(num1)*float(num2)
division=float(num1)/float(num2)
print("Addition:",addition)
print("subtraction:",subtraction)
print("multiplication:",multiplication)
print("division:",division)
first_name = input("Enter your first name: ")
last_name = input("Enter your last name: ")
full_name = first_name + " " + last_name
print("Hello, " + full_name + "! Nice to meet you.")
